package com.example.handi;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.FirebaseFirestore;

import java.util.HashMap;
import java.util.Map;

public class signup extends AppCompatActivity {

    EditText signup_username, signup_email, signup_password;
    Button signup_buttom;

    private FirebaseAuth mAuth;
    private FirebaseFirestore db;
    CentralStorage cstorage ;

    String singupUsername, signupEmail , singupPassword;
    String userId="";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_signup);
        mAuth=FirebaseAuth.getInstance();
        cstorage=new CentralStorage(signup.this);
        signup_username=findViewById(R.id.txt_username);
        signup_email=findViewById(R.id.txt_email);
        signup_password=findViewById(R.id.txt_password);

        signup_buttom=findViewById(R.id.signup_button);

        signup_buttom.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                singupUsername=String.valueOf(signup_username.getText()).trim();
                signupEmail=String.valueOf(signup_email.getText()).trim();
                singupPassword=String.valueOf(signup_password.getText()).trim();



                int error = 0;
                //check for empty fields




                if(error==0){
                    //adding in firebase
                    mAuth.createUserWithEmailAndPassword(signupEmail, singupPassword)
                            .addOnCompleteListener(signup.this,
                                    new OnCompleteListener<AuthResult>() {
                                        @Override
                                        public void onComplete(@NonNull Task<AuthResult> task) {
                                            if (task.isSuccessful()) {
                                                // logic for success
                                                userId = mAuth.getUid();// retrieving autogenerated id for newly created user
                                                cstorage = new CentralStorage(signup.this);
                                                cstorage.setData("userid",userId);
                                                // optional , verify email address by sending verification link
                                                //mAuth.getCurrentUser().sendEmailVerification();
                                                // create a model class and save the data for profiling purpose
                                                //User user = new User(userId,name,email,contact,pass); // for example
                                                //createProfile(); // write a method to upload all data into respective database
                                            } else {
                                                //logic for failed
                                                Toast.makeText(
                                                        signup.this,
                                                        "Failed "+task.getException(),
                                                        Toast.LENGTH_LONG).show();
                                            }
                                        }
                                    });
                    String val;

                    while(true){
                        val = new CentralStorage(signup.this).getData("userid");
                        if(val.equals("")){
                            CentralStorage loop = new CentralStorage(signup.this);
                            loop.clearData();
                            loop.setData("userid",mAuth.getUid());
                        }
                        else
                            break;
                    }

                    //stroing data in firestore
                    db = FirebaseFirestore.getInstance();
                    // creating map variable to store data in key-value pair
                    Map<String,Object> newUser = new HashMap<>();

                            /* in case of having data from a model class
                             newUser.put(singupUsername,user.getUserName());
                             newUser.put(,user.getUserEmail());*/

                    // in case of not having a model class

                    newUser.put("Name",singupUsername);
                    newUser.put("Email",signupEmail);
                    newUser.put("UID",val);


                    //saving data in fireStore
                    db.collection("USER")
                            .document(val).set(newUser)  // in case of using map , if not using then write multiple set() to save data
                            .addOnFailureListener(new OnFailureListener() {
                                @Override
                                public void onFailure(@NonNull Exception e) {
                                    //failure
                                    Toast.makeText(signup.this, e.getMessage(), Toast.LENGTH_LONG).show();
                                }
                            })
                            .addOnSuccessListener(new OnSuccessListener<Void>() {
                                                      @Override
                                                      public void onSuccess(Void aVoid) {
                                                          //success
                                                          Toast.makeText(signup.this, "Signed in successfully",
                                                                  Toast.LENGTH_LONG).show();

                                                          Intent in = new Intent(signup.this,MainActivity.class);
                                                          startActivity(in);
                                                          signup.this.finish();
                                                      }
                                                  }
                            );

                }
                else{
                    Toast.makeText(signup.this, "Enter all valid information",
                            Toast.LENGTH_LONG).show();
                }
            }
        });
    }
}